SET client_encoding = 'UTF8';

INSERT INTO produtos (name, category, unit, min_stock, max_stock, active) VALUES
('Luva de Procedimento M',        'EPI',                  'caixa',    30, 150, TRUE),
('Luva de Procedimento P',        'EPI',                  'caixa',    30, 150, TRUE),
('Luva de Procedimento G',        'EPI',                  'caixa',    20, 120, TRUE),
('Luva Cirurgica 7,0',            'EPI',                  'par',      20, 100, TRUE),
('Mascara Cirurgica Tripla',      'EPI',                  'caixa',    50, 200, TRUE),
('Touca Descartavel',             'EPI',                  'pacote',   30, 100, TRUE),
('Avental Cirurgico',             'EPI',                  'unidade',  15,  60, TRUE),
('Prilocaina c/ Vasoconstritor',  'Anestesico',           'caixa',    10,  80, TRUE),
('Lidocaina 2%',                  'Anestesico',           'caixa',    10,  80, TRUE),
('Articaina 4%',                  'Anestesico',           'caixa',     8,  60, TRUE),
('Resina Composta A2',            'Material Restaurador', 'seringa',  10, 100, TRUE),
('Resina Composta A3',            'Material Restaurador', 'seringa',  10, 100, TRUE),
('Resina Fluida',                 'Material Restaurador', 'seringa',   8,  60, TRUE),
('Adesivo Dentinario',            'Material Restaurador', 'frasco',    6,  40, TRUE),
('Acido Fosforico 37%',           'Material Restaurador', 'seringa',   8,  60, TRUE),
('Ionomero de Vidro',             'Material Restaurador', 'kit',       4,  30, TRUE),
('Gaze Esteril',                  'Material Cirurgico',   'pacote',   15, 120, TRUE),
('Seringa 20ml',                  'Material Cirurgico',   'caixa',    20, 100, TRUE),
('Fio de Sutura Nylon 4-0',       'Material Cirurgico',   'caixa',     5,  50, TRUE),
('Fio de Sutura Seda 4-0',        'Material Cirurgico',   'caixa',     5,  40, TRUE),
('Lencol de Borracha',            'Material Cirurgico',   'caixa',    20, 100, TRUE),
('Soro Fisiologico 0,9%',         'Material Cirurgico',   'frasco',   10,  80, TRUE),
('Alcool 70%',                    'Higienizacao',         'frasco',   20, 100, TRUE),
('Alcool 99,5%',                  'Higienizacao',         'frasco',    8,  60, TRUE),
('Clorexidina 0,12%',             'Higienizacao',         'frasco',    5,  40, TRUE),
('Matriz Metalica 0,5mm',         'Instrumentais',        'pacote',    8,  50, TRUE),
('Sugador Cirurgico Descartavel', 'Instrumentais',        'pacote',   15, 100, TRUE),
('Revelador Radiografico',        'Outros',               'frasco',    4,  30, TRUE),
('Fixador Radiografico',          'Outros',               'frasco',    4,  30, TRUE),
('Filme Radiografico Periapical', 'Outros',               'caixa',     5,  40, TRUE),
('Gesso Tipo III',                'Outros',               'pacote',   12,  80, TRUE),
('Alginato Tipo II',              'Outros',               'pacote',    8,  60, TRUE),
('Cera Utilidade No 7',           'Outros',               'pacote',    6,  50, TRUE)
ON CONFLICT (name) DO NOTHING;
