INSERT INTO solicitacao
    (id, item_id, item_nome, solicitante, cargo, data_solicitacao,
     quantidade_solicitada, unidade, justificativa, status,
     data_conclusao, responsavel, observacao)
VALUES

('SOL-001', 11, 'Resina Composta A2',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '3 hours',
    5, 'seringa',
    'Reposição para os atendimentos da semana de endodontia.',
    'pendente', NULL, NULL, NULL),

('SOL-002', 8, 'Prilocaína c/ Vasoconstritor',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '1 hour',
    2, 'caixa',
    'Estoque do CEO está baixo e há cirurgias agendadas para amanhã.',
    'pendente', NULL, NULL, NULL),

('SOL-003', 17, 'Gaze Estéril',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '40 minutes',
    3, 'pacote',
    'Cobertura pós-operatória dos pacientes da tarde.',
    'pendente', NULL, NULL, NULL),

('SOL-004', 1, 'Luva de Procedimento P',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '4 days',
    2, 'caixa',
    'Reposição rotineira do EPI do CEO.',
    'aprovada',
    NOW() - INTERVAL '3 days 22 hours',
    'Usuário Almoxarife (exemplo)', NULL),

('SOL-005', 17, 'Gaze Estéril',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '8 days',
    3, 'pacote',
    'Demanda acima do esperado durante a semana de atendimento intensivo.',
    'aprovada',
    NOW() - INTERVAL '7 days 21 hours',
    'Usuário Almoxarife (exemplo)', NULL),

('SOL-006', 23, 'Álcool 70%',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '12 days',
    2, 'frasco',
    'Higienização de superfícies entre atendimentos.',
    'aprovada',
    NOW() - INTERVAL '11 days 20 hours',
    'Usuário Almoxarife (exemplo)', NULL),

('SOL-007', 11, 'Resina Composta A2',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '15 days',
    10, 'seringa',
    'Pedido para o mês inteiro, evitar várias requisições pequenas.',
    'negada',
    NOW() - INTERVAL '14 days 22 hours',
    'Usuário Almoxarife (exemplo)',
    'Quantidade acima do limite por solicitação. Solicite no máximo 5 unidades por vez.'),

('SOL-008', 8, 'Prilocaína c/ Vasoconstritor',
    'Usuário Dentista (exemplo)', 'Dentista do CEO',
    NOW() - INTERVAL '20 days',
    4, 'caixa',
    'Manter estoque do CEO sempre cheio.',
    'negada',
    NOW() - INTERVAL '19 days 23 hours',
    'Usuário Almoxarife (exemplo)',
    'Estoque do CEO ainda está adequado. Reavaliar em 7 dias.');
